### ISSUE TITLE
Monitor always returns true

### ISSUE THREAD

**Issue by spanthetree** [mayuresh82/gocast#21]
Hi there! 

I'm testing out your application and so far it seems great! One problem though that the monitors always return true regardless of the state of the monitored application.

for example, i have the following application:

```
  - name: dns
    vip: 172.31.51.53/32
    vip_config:
      # additional per VIP BGP communities
      # bgp_communities: [ aaaa:bbbb ]
            monitor: port:tcp:12345
```
I tried multiple monitors, for example `exec:pgrep named`, `exec:/custom/script.sh`, and `port:udp:53` of course.

since i have nothing running on tcp:12345 (this can be proved with a quick ss -tulpn), i would expect the monitor to fail and the route for this vip to be withdrawn, but that isn't the case. I continue to see dns monitor succeeded messages in the system logs such as below:

` monitor.go:250] All Monitors for app: dns succeeded`

do you happen to have any ideas as to what i might be missing? I am running gocast as a systemd service using the following command:

`ExecStart=gocast -logtostderr -v=2 -config /etc/gocast/config.yaml`

Thank you in advance!
