### ISSUE TITLE
seemingly functional, however services are not reachable?

### ISSUE THREAD

**Issue by endigma** [mayuresh82/gocast#9]
setup:
- nomad & consul
- opnsense
- gocast running as nomad job

config:
```yml
agent:
  listen_addr: :9080
  monitor_interval: 10s
  cleanup_timer: 15m
  consul_addr: http://localhost:8500/v1
  consul_query_interval: 1m

bgp:
  local_as: 65000 
  remote_as: 65000
  origin: igp

apps:
  - name: app1
    vip: 192.168.1.99/32
    monitor: port:tcp:6000
```
---

# Problem

I've verified that my config is as it should be to the best of my knowledge, and gocast seems to be creating BGP routes, however every route only exposes 22 (ssh) and 9080 (gocast api). I've set up a nomad job with service tags that suggest it should be provided a VIP by gocast, however the service on port 4040 is inaccessible, nmap scans show the same (22, 9080) as the VIP created for gocast itself.

# I've verified
- consul connectivity is working to at least some degree, gocast logs cite creating a route
- the route created by gocast for gocast works to contact ssh and gocast

# I've tried
- restarting
- redeploying jobs
- redefining job
- reinstalling frr on opnsense

---
# Extra info

## bgp config on opnsense (frr)
```
Building configuration...

Current configuration:
!
frr version 7.4
frr defaults traditional
hostname maeve.admincat.ca
log syslog informational
!
router bgp 65000
 bgp router-id 192.168.1.1
 no bgp ebgp-requires-policy
 neighbor 192.168.1.61 remote-as 65000
 neighbor 192.168.1.62 remote-as 65000
 neighbor 192.168.1.63 remote-as 65000
 !
 address-family ipv4 unicast
  network 192.168.1.0/24
  neighbor 192.168.1.61 next-hop-self
  neighbor 192.168.1.62 next-hop-self
  neighbor 192.168.1.63 next-hop-self
 exit-address-family
!
line vty
!
end
```
